### PR TITLE
Update localization.ru.lua

### PR DESCRIPTION
**Pull request by Hollicsh**
Minor fixes.

### CODE REVIEW

**Comment by QartemisT** [comment]
Hi there,

I noticed you updated a "misc translation", which is meant to be a direct quote from the game. Are you just fixing translations that are already there, or getting them from the actual game?

**Comment by Hollicsh** [comment]
Hey !
In this case, I corrected typos in some words and simply translated one phrase. I think it sounds like that.

**Comment by QartemisT** [comment]
The main ones in this that have to be EXACT as the in-game versions are;
- HordeVictory		
- specWarnSubmergeSoon	

Can you confirm if this is the case or?

**Comment by Hollicsh** [comment]
Now it's right

**Pull request merged**
